DROP TABLE IF EXISTS `img_resize`;

CREATE TABLE `img_resize` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `UPLOAD` MEDIUMTEXT NULL DEFAULT NULL,
  `UNIQ_ID` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`id`)
);

